name: Slither

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-slither:
    runs-on: ubuntu-latest
    name: Solidity Security
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Slither Static Analysis
        uses: luisfontes19/slither-static-analysis-action@v0.3.2
        with:
          slither-version: '0.6.13'
          run-npm-install: true
          high-threshold: 1
          medium-threshold: 1
          low-threshold: 1
          optimization-threshold: 1
          informative-threshold: 10
          projectPath: "."